"""add user preference columns

Revision ID: 3d7fb9637c72
Revises: ecd06b08341b
Create Date: 2026-07-01 12:22:41.073538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7fb9637c72'
down_revision = 'ecd06b08341b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pref_contest_reminders', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('pref_weekly_report',     sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('pref_streak_alerts',     sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('pref_platform_sync',     sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('pref_public_profile',    sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('pref_show_streak',       sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('pref_show_ratings',      sa.Boolean(), nullable=False, server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pref_show_ratings')
        batch_op.drop_column('pref_show_streak')
        batch_op.drop_column('pref_public_profile')
        batch_op.drop_column('pref_platform_sync')
        batch_op.drop_column('pref_streak_alerts')
        batch_op.drop_column('pref_weekly_report')
        batch_op.drop_column('pref_contest_reminders')

    # ### end Alembic commands ###
