"""add cached fields to platform_stat

Revision ID: 69e150d522b2
Revises: 35c7b57043c7
Create Date: 2026-06-28 14:24:54.371653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e150d522b2'
down_revision = '35c7b57043c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('calendar_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_stats', schema=None) as batch_op:
        batch_op.drop_column('last_synced_at')
        batch_op.drop_column('calendar_data')
        batch_op.drop_column('skill_data')

    # ### end Alembic commands ###
