"""add ai_responses cache table

Revision ID: ecd06b08341b
Revises: 69e150d522b2
Create Date: 2026-06-30 21:54:58.892939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd06b08341b'
down_revision = '69e150d522b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_responses_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_responses_user_id'))

    op.drop_table('ai_responses')
    # ### end Alembic commands ###
